/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:695737f7-e397-461f-83bb-941647066b7e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_W5wzBGiO9",
    "aws_user_pools_web_client_id": "4est6pmoscbpmvond25ags9uk6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://whdjc2ayejcxfpybbmv6o2qlgy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-q7oujarw6ffytl4himojqkxww4",
    "aws_user_files_s3_bucket": "quikyempresanuevo-storage-216a55a9170813-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
